services:
  gobeh_backend:
    build:
      context: gobeh
    restart: always
    secrets:
      - db-password
    volumes:
      - ./gobeh:/gobeh
    ports:
      - 6969:8000
    depends_on:
      gobeh_database:
        condition: service_healthy

  gobeh_console:
    build:
      context: console
    restart: always
    secrets:
      - db-password
    volumes:
      - ./console:/console
    depends_on:
      gobeh_database:
        condition: service_healthy

  gobeh_database:
    image: postgres
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=gobeh
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:

secrets:
  db-password:
    file: database/password.txt